import { GetServerSideProps } from "next";
import Head from "next/head";
import Link from "next/link";
import AddRead from "../../components/AddRead";
import styles from "../../styles/Groups.module.css";

interface Read {
  id: string;
  group: string;
  name: string;
}

interface GroupPageProps {
  id: string;
  name: string;
  reads: Read[];
}

export default function GroupPage({ id, name, reads }: GroupPageProps) {
  return (
    <div className={styles.container}>
      <Head>
        <title>{name}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className={styles.main}>
        <h1>{name}</h1>
        <div>
          <h2>Join Code</h2>
          <p>{id}</p>
        </div>
        <div>
          <h2>Add New Reads</h2>
          <AddRead group={id} />
        </div>
        <div>
          <h2>Group&apos;s Reads</h2>
          {reads.map((read) => (
            <div className={styles.readLink} key={read.id}>
              <Link href={`/reads/${read.id}`}>
                <a>{read.name}</a>
              </Link>
            </div>
          ))}
        </div>
      </div>
    </div>
  );
}

export const getServerSideProps: GetServerSideProps = async (context) => {
  const groupRes = await fetch(
    `http://localhost:3001/groups/${context.params!.id}`
  );
  const group = await groupRes.json();

  if (group.err) {
    return {
      notFound: true,
    };
  }

  const groupReadsRes = await fetch(
    `http://localhost:3001/reads/group/${context.params!.id}`
  );
  const reads = await groupReadsRes.json();

  return {
    props: {
      ...group,
      reads,
    },
  };
};
