import {GetServerSideProps} from 'next';
import Head from 'next/head'
import Link from 'next/link'
import useAuth from '../../hooks/auth';
import styles from '../../styles/Groups.module.css'

interface Read {
    id: string;
    group: string;
    name: string;
}

interface GroupPageProps {
    id: string;
    name: string;
    reads: Read[]
}

export default function GroupPage({id, name, reads}: GroupPageProps) {
  const { authenticated } = useAuth();

  return (
    <div className={styles.container}>
      <Head>
        <title>{name}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div>
        <h1>{name}</h1>
        {reads.map(read => <Link key={read.id} href={`/reads/${read.id}`}><a>{read.name}</a></Link>)}
      </div>
        
    </div>
  )
}

export const getServerSideProps: GetServerSideProps = async (context) => {
    const groupRes = await fetch(`http://localhost:3001/groups/${context.params!.id}`)
    const group = await groupRes.json()
  
    if (group.err) {
      return {
        notFound: true,
      }
    }

    const groupReadsRes = await fetch(`http://localhost:3001/reads/group/${context.params!.id}`)
    const reads = await groupReadsRes.json()

    console.log(reads)

    return {
      props: {
          ...group,
          reads
      },
    }
  }
  
