import {GetServerSideProps} from 'next';
import Head from 'next/head'
import useAuth from '../../hooks/auth';
import styles from '../../styles/Groups.module.css'

interface Message {
    id: string,
    owner: string,
    read: string,
    progress: number,
    content: string,
    createdAt: number
}

interface ReadPageProps {
    id: string;
    name: string;
    read: string;
    messages: Message[]
}

export default function ReadPage({id, name, messages}: ReadPageProps) {
  const { authenticated } = useAuth();

  return (
    <div className={styles.container}>
      <Head>
        <title>{name}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div>
        <h1>{name}</h1>
        {messages.map(message => <p key={message.id}>{message.content} - {message.progress}</p>)}
      </div>
        
    </div>
  )
}

export const getServerSideProps: GetServerSideProps = async (context) => {
    const readRes = await fetch(`http://localhost:3001/reads/${context.params!.id}`)
    const read = await readRes.json()
  
    if (read.err) {
      return {
        notFound: true,
      }
    }

    const messagesRes = await fetch(`http://localhost:3001/messages/${context.params!.id}`)
    console.log(messagesRes)
    const messages = await messagesRes.json()
    // Sort by progress and then by createdAt
    messages.sort((a: Message, b: Message) => b.progress - a.progress || b.createdAt - a.createdAt)

    return {
      props: {
          ...read,
          messages
      },
    }
  }
  
