import Head from 'next/head'
import Link from 'next/link'
import useAuth from '../hooks/auth'
import styles from '../styles/Home.module.css'

export default function Home() {
  const {authenticated, logout} = useAuth();

  return (
    <div className={styles.container}>
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1>Home</h1>
      { authenticated ? <button onClick={e => logout()}>Logout</button> : <Link href="/login"><a>Sign In</a></Link> }
    </div>
  )
}
